### ISSUE TITLE
Shortcuts from a node to /mnt/overlay and /mnt/override ("Related resources")

### ISSUE THREAD

**Issue by stoerr** [ist-dresden/composum-nodes#147]
One of the outstanding features of the browser in comparison to AEM's CRX-DE lite is that you can view the result of the [Sling resource merger](https://sling.apache.org/documentation/bundles/resource-merger.html) in /mnt/override and /mnt/overlay . This makes it easier to check whether the outcome of using sling:resourceSuperType or an overlay is exactly as expected.

But to get there you have currently to either click yourself through the tree, or change the path in the URL in the browser, since there is not even a way to use the search field to locate them. So I suggest to create some kind of shortcut button going from a resource in /apps or /libs to the corresponding place in /mnt/overlay, and from a resource with a sling:resourceSuperType to the corresponding place in /mnt/override - and maybe also going backwards from there to the original resource.

This could be done as a drop down list next to the breadcrumbs, which lists the following places:
- if the resource is below one of the nodes of the resolver search path or /mnt/overlay, it could list all places according to the search path where a corresponding resource is found, and /mnt/overlay (excluding the place of the currently shown resource).
- /mnt/override if it's somewhere else except /mnt/overlay, and the resource path with /mnt/override removed, if it's below /mnt/override .

**Comment by stoerr** [comment]
Let's try an example to see what is needed. Let's say we develop a component some/component in /apps/some/component which overrides some stuff in /libs/some/component. /libs/some/component has a sling:resourceSuperType some/basecomponent. A page at /content/somepage/jcr:content/instance has a sling:resourceType some/component which we use to see the effects of changes.  So we want to have the following shortcuts:

- /content/somepage/jcr:content/instance has /libs/some/component , /apps/some/component and /mnt/overlay/some/component . (No /mnt/override since it does not have a sling:resourceSuperType).
- /apps/some/component has /libs/some/component and /mnt/overlay/some/component .
- /libs/some/component has /apps/some/component and /mnt/overlay/some/component and /mnt/override/libs/some/component (since it has sling:resourceSuperType).
- /mnt/overlay/some/component has /apps/some/component and /libs/some/component
- /mnt/override/libs/some/component has /libs/some/component and /apps/some/component

Additionally it makes sense to save the latest path outside /apps and /libs where we did this switching (that would normally be /content/somepage/jcr:content/instance in our example) to have an easy way to go back to the component instance.
We should also use the configured searchpath instead of hardcoding /apps and /libs.

**Comment by ist-rw** [comment]
implementation done, release 2.0

**Comment by ist-rw** [comment]
Implementation added. Overlays can now be created as a copy of the base implementation or removed directly from the browser. (release 2.3.0)
