### ISSUE TITLE
Not possible to trigger replication / distribution

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum-nodes#286]
A feature that I have been missing so far is to trigger a replication / distribution from the Composum browser. Maybe I haven't found it yet? Would be a very handy addition

**Comment by royteeuwen** [comment]
Fixed by https://github.com/ist-dresden/composum-nodes/pull/287

**Comment by stoerr** [comment]
Integrated into Composum Nodes release 4.1.3 .

@royteeuwen Thank you very much for your contribution! 
I improved it a little with https://github.com/ist-dresden/composum-nodes/pull/293 to display a success message, too. Could you perhaps try that? I'm not very sure whether the format /bin/replicate.json returns changes over the AEM versions. Unfortunately I couldn't convince it to actually return JSON, as the URL says. 😞 This just changes /apps/composum/nodes/browser/components/extra-actions/clientlib/js/extra-actions.js , so you could also replace that file by the [new content](https://github.com/ist-dresden/composum-nodes/blob/feature/display-activation/package/aem/src/main/content/jcr_root/apps/composum/nodes/browser/components/extra-actions/clientlib/js/extra-actions.js) to try it out.

**Comment by royteeuwen** [comment]
@stoerr  did you try this out on an AEMaaCS SDK? I get back the following response, and so the following error popup "Unparseable response on activate"

{"path":["/content/my-site/fr"],"artifactId":[],"status.message":"Replication started for /content/my-site/fr\n","status.code":200}

**Comment by royteeuwen** [comment]
https://github.com/ist-dresden/composum-nodes/pull/294

**Comment by stoerr** [comment]
@royteeuwen Thank you, good that you tested and improved that! Nice that Adobe later fixed /bin/replicate.json to return JSON.

@ist-rw Do you want to have a look at https://github.com/ist-dresden/composum-nodes/pull/294 ? I also set our branch [feature/fix-extra-actions](https://github.com/ist-dresden/composum-nodes/tree/feature/fix-extra-actions) to that, to make it easier to test. But we checked that on AEM 6.5.x and AEMaaCS, so it's likely to work, and I think we can just merge it if you don't object to something in the Javascript.

**Comment by stoerr** [comment]
With the new release https://github.com/ist-dresden/composum-nodes/releases/tag/composum-nodes-4.2.1 there is the big closing time for issues. :-)
