### ISSUE TITLE
The product interfaces org.apache.jackrabbit.api.security.user.Group, org.apache.jackrabbit.api.security.user.Authorizable and org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType should not be implemented by custom code.

### ISSUE THREAD

**Issue by manuel-sanchez-vilt** [ist-dresden/composum-nodes#310]
I launch a non-production code quality pipeline in Cloud Manager and I get the following critical bugs:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/vilt2/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/vilt2/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">

File Location | Line Number | Issue | Type | Severity | Effort | Rule | Tags | Documentation
-- | -- | -- | -- | -- | -- | -- | -- | --
com/composum/nodes:composum-nodes-aem-package:4.2.1 | 0 | The product interface   org.apache.jackrabbit.api.security.user.Group annotated with @ProviderType   should not be implemented by custom code. Detected in   com.composum.sling.core.usermanagement.service.GroupFacade contained in   /apps/composum/nodes/install/composum-nodes-usermgr-bundle-4.2.1.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en
com/composum/nodes:composum-nodes-aem-package:4.2.1 | 0 | The product   interface org.apache.jackrabbit.api.security.user.Authorizable annotated with   @ProviderType should not be implemented by custom code. Detected in   com.composum.sling.core.usermanagement.service.ServiceUser contained in   /apps/composum/nodes/install/composum-nodes-usermgr-bundle-4.2.1.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en
com/composum/nodes:composum-nodes-aem-package:4.2.1 | 0 | The product interface   org.apache.jackrabbit.api.security.user.Query annotated with @ProviderType   should not be implemented by custom code. Detected in   com.composum.sling.core.usermanagement.service.impl.AuthorizablesImpl$1   contained in /apps/composum/nodes/install/composum-nodes-usermgr-bundle-4.2.1.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en
com/composum/nodes:composum-nodes-aem-package:4.2.1 | 0 | The product   interface org.apache.jackrabbit.api.security.user.Query annotated with   @ProviderType should not be implemented by custom code. Detected in   com.composum.sling.nodes.servlet.SecurityServlet$GetPrincipals$1 contained in   /apps/composum/nodes/install/composum-nodes-console-bundle-4.2.1.jar. | Bug | Critical | 30m | CQRules:CQBP-84 | cqsoftwarequality | https://www.adobe.com/go/aem_cmcq_cqbp-84_en

</body>

</html>

**Comment by royteeuwen** [comment]
To check if this would be resolved by following ticket:
https://issues.apache.org/jira/browse/OAK-10448

**Comment by kwin** [comment]
The last two I consider correct qualifications (i.e. Group and Authorizable)should only be implemented by Provider bundles of Jackrabbit API). Therefore I recommend trying to get rid of those implementations (and in the worst case use the workaround like https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/proxy.html). `Query` I consider a false positive, which doesn't require a fix in the Composum (just an updated Oak version).

**Comment by royteeuwen** [comment]
thanks for the update @kwin , I'll check if I can refactor them

**Comment by stoerr** [comment]
I created a [new Nodes Release 4.2.2](https://github.com/ist-dresden/composum-nodes/releases/tag/composum-nodes-4.2.2) with that, so I'll mark that as fixed and close it. Thank you @manuel-sanchez-vilt for reporting and thanks to @royteeuwen for fixing it!
